### ISSUE TITLE
plot_as_profile2d() bug

### ISSUE THREAD

**Issue by dvezinet** [ToFuProject/bsplines2d#21]
Purely radial non-spectro emissivity does not get plotted properly as profile_2d:

![image](https://github.com/ToFuProject/bsplines2d/assets/112180133/2466fe2a-7289-4e55-ab42-a905cedd3dc7)

![image](https://github.com/ToFuProject/bsplines2d/assets/112180133/dc59f029-efd5-4373-a7d8-993c476cb331)

**Comment by Didou09** [comment]
Was due to wrong input
